In [11]:
import numpy as np

def cholesky(A):
    if A.shape[0] == 1:
        return np.sqrt(A[0,0])

    A_tl = A[0,0]
    A_bl = A[1:,0]
    A_br = A[1:,1:]

    L_tl = np.sqrt(A_tl)
    L_bl = (A_bl/np.sqrt(A_tl))
    L_br = cholesky(A_br-np.dot(L_bl.reshape(-1,1),L_bl.reshape((1,-1)))) # recursion

    L = np.eye(len(A))
    L[0, 0]  = L_tl
    L[1:,0]  = L_bl
    L[1:,1:] = L_br
    return L

A = np.array([[4, 12, -16], # example from wikipedia
              [12, 37, -43], 
              [-16, -43, 98]])

print(cholesky(A))

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]
