In [9]:
import numpy as np

def cholesky(A):
    n = len(A)

    # Create zero matrix for L
    L = [[0.0] * n for i in range(n)]

    # Perform the Cholesky decomposition
    for i in range(n):
        for k in range(i+1):
            tmp_sum = sum(L[i][j] * L[k][j] for j in range(k))
            
            if (i == k): # Diagonal elements
                L[i][k] = np.sqrt(A[i][i] - tmp_sum)
            else:
                L[i][k] = (1.0 / L[k][k] * (A[i][k] - tmp_sum))
    return np.asarray(L)

A = np.array([[4, 12, -16], # example from wikipedia
              [12, 37, -43], 
              [-16, -43, 98]])

print(cholesky(A))

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]
